default: &default
  adapter: mysql2
  character: utf8mb4
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: scoutter_development

test:
  <<: *default
  database: scoutter_test

production:
  <<: *default
  database: scoutter_production
  username: scoutter
  password: <%= ENV['SCOUTTER_DATABASE_PASSWORD'] %>
